spring.application.name=restfulhousekeeping
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
server.port=50000

calendar.import.fixed-delay=PT5M
calendar.import.initial-delay=PT1M

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
